flags: {}
extra-package-dbs: []
packages:
- '.'
- location: ./vendor/haskell-ascii-progress
  extra-dep: true
extra-deps:
- c-storable-deriving-0.1.3
- pqueue-1.3.1.1
- reactive-banana-1.1.0.1
resolver: lts-6.7
